"""Signed scan results: a verdict a third party can check.

WHAT IS SIGNED, AND WHY IT IS NOT THE WHOLE FILE. The signature covers a
verdict BODY that excludes everything non-reproducible: the wall-clock, the
hostname, the file paths, the duration. Those live in an unsigned envelope
beside it.

That split is what makes "same input, same output, byte identical" a testable
claim rather than a slogan. Ed25519 is deterministic, so the same body under
the same key produces the same 64 signature bytes every time — and a body
containing a timestamp could never do that. Signing the whole document would
mean the signature changed on every run, which proves the machine said it and
nothing about reproducibility.

The target is recorded as a DIGEST, not a string. A command line can contain a
path that identifies a person, and a signed record is the thing most likely to
be forwarded to someone who should not learn it.

KEYS ARE NEVER GENERATED BY A SCAN. `mcpscan keygen` writes one deliberately.
A scan with no key emits an unsigned record and says so; it does not create key
material as a side effect, which on a shared CI runner would be a liability
rather than a convenience.
"""

from __future__ import annotations

import hashlib
import json
import os
import stat
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

from mcpscan import __version__
from mcpscan.errors import McpScanError
from mcpscan.models import ScanResult
from mcpscan.ruleset import RULESET_VERSION, ruleset_digest
from mcpscan.scoring import effective_severity
from mcpscan.tiers import grade_is_assessable

RESULT_FORMAT = 1

EXIT_VERIFIED = 0
EXIT_BAD_SIGNATURE = 1
EXIT_CANNOT_VERIFY = 2


class SigningError(McpScanError):
    pass


# ----------------------------------------------------------------- keys


def default_key_path() -> Path:
    return Path(os.environ.get("MCPSCAN_KEY", Path.home() / ".mcpscan" / "signing.key"))


def generate_key(path: Path) -> str:
    """Write a new private key. Refuses to overwrite one."""
    if path.exists():
        raise SigningError(f"{path} already exists; refusing to overwrite a signing key.")
    key = Ed25519PrivateKey.generate()
    path.parent.mkdir(parents=True, exist_ok=True)
    pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    # Written 0600 from the start, not chmod'ed afterwards: between the two
    # there is a window where the key is world-readable.
    handle = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(handle, "wb") as file:
        file.write(pem)
    return public_key_pem(key)


def load_private_key(path: Path) -> Ed25519PrivateKey:
    if not path.exists():
        raise SigningError(f"No signing key at {path}. Create one with `mcpscan keygen`.")
    if os.name != "nt":
        mode = stat.S_IMODE(path.stat().st_mode)
        if mode & 0o077:
            raise SigningError(
                f"Signing key {path} is mode {mode:o}; it must be owner-only (chmod 600)."
            )
    key = serialization.load_pem_private_key(path.read_bytes(), password=None)
    if not isinstance(key, Ed25519PrivateKey):
        raise SigningError(f"{path} is not an Ed25519 private key.")
    return key


def public_key_pem(key: Ed25519PrivateKey | Ed25519PublicKey) -> str:
    public = key.public_key() if isinstance(key, Ed25519PrivateKey) else key
    return public.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode("ascii")


def load_public_key(pem: str) -> Ed25519PublicKey:
    key = serialization.load_pem_public_key(pem.encode("ascii"))
    if not isinstance(key, Ed25519PublicKey):
        raise SigningError("Not an Ed25519 public key.")
    return key


# ----------------------------------------------------------------- the body


def target_digest(result: ScanResult) -> str:
    """Identify the target without reproducing it.

    A command line can contain a home directory, which names a person. The
    digest is stable for the same target and tells a reader nothing else.
    """
    parts = [
        result.target.kind.value,
        result.target.transport.value,
        result.target.url or "",
        " ".join(result.target.command or []),
    ]
    return hashlib.sha256("\x1f".join(parts).encode("utf-8")).hexdigest()


def verdict_body(result: ScanResult) -> dict[str, Any]:
    """Everything a verdict rests on, and nothing that varies between runs."""
    return {
        "result_format": RESULT_FORMAT,
        "mcpscan_version": __version__,
        "ruleset_version": RULESET_VERSION,
        "ruleset_digest": ruleset_digest(),
        "tier": result.tier.value,
        "target_digest": target_digest(result),
        "surface_digest": hashlib.sha256(
            json.dumps(
                result.surface.model_dump(mode="json"), sort_keys=True, separators=(",", ":")
            ).encode()
        ).hexdigest(),
        "grade": result.grade if grade_is_assessable(result.checks_not_run) else None,
        "grade_assessed": grade_is_assessable(result.checks_not_run),
        "counts": dict(sorted(result.counts.items())),
        "checks_not_run": sorted(
            (dict(sorted(item.items())) for item in result.checks_not_run),
            key=lambda item: item.get("check_id", ""),
        ),
        "findings": [
            {
                "id": finding.id,
                "severity": (finding.original_severity or finding.severity).value,
                "adjusted_severity": effective_severity(finding).value,
                "contextual_verdict": finding.contextual_verdict.value,
                "capability": finding.capability.value,
                "scope": finding.scope.value,
                "owasp_mcp": finding.owasp_mcp,
                "target": finding.target,
                "evidence_sha256": hashlib.sha256(finding.evidence.encode("utf-8")).hexdigest(),
                "payload_stored": finding.payload_stored,
            }
            for finding in result.findings
        ],
    }


def canonical_body(body: dict[str, Any]) -> bytes:
    return json.dumps(body, sort_keys=True, separators=(",", ":")).encode("utf-8")


def body_digest(body: dict[str, Any]) -> str:
    return hashlib.sha256(canonical_body(body)).hexdigest()


# ----------------------------------------------------------------- the record


def build_result_record(
    result: ScanResult,
    *,
    key: Ed25519PrivateKey | None,
    signed_at: str | None = None,
    target_label: str | None = None,
) -> dict[str, Any]:
    body = verdict_body(result)
    envelope: dict[str, Any] = {
        # Everything here is outside the signature, and the record says so.
        "signed_at": signed_at or datetime.now(UTC).isoformat(timespec="seconds"),
        "target_label": target_label,
        "mcpscan_version": __version__,
        "unsigned_fields": ["signed_at", "target_label", "mcpscan_version", "unsigned_fields"],
    }
    record: dict[str, Any] = {
        "record_format": RESULT_FORMAT,
        "envelope": envelope,
        "body": body,
        "body_sha256": body_digest(body),
    }
    if key is None:
        record["signature"] = None
        record["public_key_pem"] = None
        record["signed"] = False
        return record
    record["signature"] = key.sign(canonical_body(body)).hex()
    record["public_key_pem"] = public_key_pem(key)
    record["signed"] = True
    return record


def render_record(record: dict[str, Any]) -> str:
    return json.dumps(record, indent=2, sort_keys=True) + "\n"


# ----------------------------------------------------------------- verification


class VerificationResult:
    def __init__(self, exit_code: int, lines: list[str]) -> None:
        self.exit_code = exit_code
        self.lines = lines

    def report(self) -> str:
        return "\n".join(self.lines) + "\n"


def verify_record(
    record: dict[str, Any], *, expect_pubkey_pem: str | None = None
) -> VerificationResult:
    """Check a record. 0 verified, 1 bad signature, 2 cannot verify."""
    lines: list[str] = []

    if record.get("record_format") != RESULT_FORMAT:
        return VerificationResult(
            EXIT_CANNOT_VERIFY,
            [
                f"CANNOT VERIFY  record_format {record.get('record_format')!r} is not {RESULT_FORMAT}"
            ],
        )
    body = record.get("body")
    if not isinstance(body, dict):
        return VerificationResult(EXIT_CANNOT_VERIFY, ["CANNOT VERIFY  record has no body"])

    recomputed = body_digest(body)
    if recomputed != record.get("body_sha256"):
        return VerificationResult(
            EXIT_BAD_SIGNATURE,
            [
                f"TAMPERED  body digest is {recomputed[:16]}…, record claims {str(record.get('body_sha256'))[:16]}…"
            ],
        )
    lines.append(f"body digest        {recomputed}")

    if not record.get("signed"):
        # Never 0. An unsigned record is not a verified one, and reporting it
        # as a pass is how "we verify our scans" becomes untrue.
        lines.append("CANNOT VERIFY  this record is unsigned; there is nothing to check it against")
        return VerificationResult(EXIT_CANNOT_VERIFY, lines)

    pem = expect_pubkey_pem or record.get("public_key_pem")
    if not pem:
        return VerificationResult(EXIT_CANNOT_VERIFY, [*lines, "CANNOT VERIFY  no public key"])
    if (
        expect_pubkey_pem
        and record.get("public_key_pem")
        and expect_pubkey_pem.strip() != str(record["public_key_pem"]).strip()
    ):
        return VerificationResult(
            EXIT_BAD_SIGNATURE,
            [*lines, "TAMPERED  record was signed by a different key than the one pinned"],
        )
    try:
        load_public_key(pem).verify(bytes.fromhex(str(record["signature"])), canonical_body(body))
    except (InvalidSignature, ValueError) as exc:
        return VerificationResult(
            EXIT_BAD_SIGNATURE, [*lines, f"TAMPERED  signature does not verify ({exc})"]
        )

    lines.append(f"ruleset            v{body['ruleset_version']} digest {body['ruleset_digest']}")
    lines.append(f"tier               {body['tier']}")
    lines.append(
        "grade              "
        + (str(body["grade"]) if body["grade_assessed"] else "not assessed (checks did not run)")
    )
    lines.append(
        "outside signature  " + ", ".join(record.get("envelope", {}).get("unsigned_fields", []))
    )
    lines.append("VERIFIED  the body is intact and signed by this key")
    return VerificationResult(EXIT_VERIFIED, lines)
